Repository ILGOB/Plinic-iOS, pull requests merged in 2022-10, with the labels that each got.

#52 Feature/navigation/#51
  Assets.xcassets/AppIcon.appiconset/Contents.json
  Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  Assets.xcassets/AppIcon.appiconset/Icon-120 1.png
  Assets.xcassets/AppIcon.appiconset/Icon-120.png
  Assets.xcassets/AppIcon.appiconset/Icon-180.png
  Assets.xcassets/AppIcon.appiconset/Icon-40.png
  Assets.xcassets/AppIcon.appiconset/Icon-58.png
  Assets.xcassets/AppIcon.appiconset/Icon-60.png
  Assets.xcassets/AppIcon.appiconset/Icon-80.png
  Assets.xcassets/AppIcon.appiconset/Icon-87.png
  Plinic.xcodeproj/project.pbxproj
  Plinic/ContentView.swift
  Plinic/Extensions/Keyboards.swift
  Plinic/Extensions/PlinicColors.swift
  Plinic/Navigation/Post.swift
  Plinic/Navigation/Search.swift
  Plinic/Navigation/User.swift
  Plinic/login/LoginContentView.swift
  Plinic/post/postContentView.swift
  Plinic/post/postCreate.swift
  Plinic/post/postViews/postDetailInfo.swift
  Plinic/post/postViews/postInfo.swift
  Plinic/search/searchContentView.swift
  Plinic/search/searchViews/searchBar.swift
  Plinic/search/searchViews/searchResult.swift
  Plinic/search/searchViews/userTopResult.swift
  Plinic/user/UserContentView.swift
  Plinic/user/UserProfile.swift
  Plinic/user/playlistCreate.swift
  Plinic/user/userContentView.swift
  Plinic/user/userProfile.swift
  Plinic/user/userViews/UserInfo.swift
  Plinic/user/userViews/genreInfo.swift
  Plinic/user/userViews/playlistInfo.swift
  Plinic/user/userViews/thumbnail.swift
  Plinic/user/userViews/userInfo.swift
  Plinic/user/userViews/userMyPlaylist.swift
  Plinic/user/userViews/userMyPost.swift
Labels: 디자인, 리팩토링, 개발

#55 협업을 위한 중간 머지
  Assets.xcassets/profileDefault.imageset/Contents.json
  Assets.xcassets/profileDefault.imageset/Icon-120.png
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/BackgroundVideo.swift
  Plinic/Back-End/PostList.swift
  Plinic/Navigation/Post.swift
  Plinic/login/loginContentView.swift
  Plinic/post/postContentView.swift
  Plinic/post/postViews/PostHeader.swift
  Plinic/post/postViews/postDetailInfo.swift
  Plinic/post/postViews/postInfo.swift
  Plinic/search/searchContentView.swift
  Plinic/search/searchViews/searchResult.swift
  Plinic/user/userViews/thumbnail.swift
  Plinic/videoBackground/VideoBackgroundView.swift
Labels: API, 개발

#63 ♻️ (jaewon/feature/refactor) 기능 개발하기전 네이밍 관련 리팩토링 수행
  Plinic.xcodeproj/project.pbxproj
  Plinic/ContentView.swift
  Plinic/Login/KakaoAuthVM.swift
  Plinic/Login/LoginViews/LoginButton.swift
  Plinic/Login/MyAppDelegate.swift
  Plinic/Login/MySceneDelegate.swift
  Plinic/Login/loginContentView.swift
  Plinic/Navigation/UserView.swift
  Plinic/Post/PostDetail.swift
  Plinic/Post/PostViews/PostHeader.swift
  Plinic/Post/PostViews/PostInfoView.swift
  Plinic/Post/PostViews/postDetailInfo.swift
  Plinic/Post/postContentView.swift
  Plinic/Post/postCreate.swift
  Plinic/Search/SearchViews/GenreThumbnail.swift
  Plinic/Search/SearchViews/SearchDetail.swift
  Plinic/Search/SearchViews/UserResult.swift
  Plinic/Search/SearchViews/searchBar.swift
  Plinic/Search/SearchViews/searchResult.swift
  Plinic/Search/SearchViews/userTopResult.swift
  Plinic/Search/searchContentView.swift
  Plinic/User/UserPlaylist.swift
  Plinic/User/UserProfile.swift
  Plinic/User/UserViews/GenreTagView.swift
  Plinic/User/UserViews/Thumbnail.swift
  Plinic/User/UserViews/UserContents.swift
  Plinic/User/UserViews/UserInfoView.swift
  Plinic/User/UserViews/UserMyPlaylistView.swift
  Plinic/User/UserViews/UserMyPostView.swift
  Plinic/User/UserViews/chooseGenre.swift
  Plinic/User/UserViews/playlistInfo.swift
  Plinic/User/playlistCreate.swift
  Plinic/User/userContentView.swift
  Plinic/VideoBackground/VideoBackgroundView.swift
Labels: 리팩토링

#66 (feature/back-end/#53) 게시물 상세 API 받아오기
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/PostDetailData.swift
  Plinic/Post/PostDetail.swift
  Plinic/Post/PostViews/PostDetailInfo.swift
  Plinic/Post/PostViews/PostInfoView.swift
  Plinic/Post/PostViews/postDetailInfo.swift
  Plinic/Post/postContentView.swift
  Plinic/User/UserViews/GenreTagView.swift
  Plinic/User/UserViews/PlaylistInfo.swift
  Plinic/User/UserViews/UserMyPostView.swift
Labels: API

#65 :art: (jaewon/feature/login) 카카오 로그인 버튼 고화질로 변경
  Assets.xcassets/kakao_login_large_wide.imageset/Contents.json
  Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide.png
  Plinic/Login/LoginViews/LoginButton.swift
Labels: 디자인

#64 :art: (jaewon/feature/back-end/#53) 통신관련 파일 구조 개선
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/PostAPI/DTO/Author.swift
  Plinic/Back-End/PostAPI/DTO/Playlist.swift
  Plinic/Back-End/PostAPI/DTO/Post.swift
  Plinic/Back-End/PostAPI/DTO/PostList.swift
  Plinic/Back-End/PostAPI/PostAPI.swift
  Plinic/Back-End/PostList.swift
  Plinic/Back-End/RandomAPI/DTO/BackgroundVideo.swift
  Plinic/Back-End/RandomAPI/RandomAPI.swift
  Plinic/Navigation/PostView.swift
  Plinic/Post/postContentView.swift
  Plinic/VideoBackground/VideoBackgroundView.swift
Labels: 리팩토링, API

#67 :art: :bug: (feature/back-end/#53) 통신을 위한 파일들 구조 개선 & View 기능 확장 & #58 이슈 해결
  Config.xcconfig
  Plinic.xcodeproj/project.pbxproj
  Plinic.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Plinic.xcodeproj/project.xcworkspace/xcuserdata/yukyungdeok.xcuserdatad/UserInterfaceState.xcuserstate
  Plinic.xcodeproj/xcuserdata/macbookair.xcuserdatad/xcschemes/xcschememanagement.plist
  Plinic.xcodeproj/xcuserdata/yukyungdeok.xcuserdatad/xcschemes/xcschememanagement.plist
  Plinic/Back-End/Network/NetworkService.swift
  Plinic/Back-End/PostAPI/PostAPI.swift
  Plinic/Extensions/View+.swift
  Plinic/Extensions/ViewDidLoadModifier.swift
  Plinic/Info.plist
  Plinic/Post/postContentView.swift
Labels: 리팩토링, API

#69 (feature/back-end/#53) 파일 구조 수정, 이름 변경 및 최신 공지사항 통신 해결
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/Network/NetworkService.swift
  Plinic/Back-End/NoticeAPI/DTO/RecentNotice.swift
  Plinic/Back-End/NoticeAPI/NoticeAPI.swift
  Plinic/Back-End/PostAPI/DTO/PlaylistDetial.swift
  Plinic/Back-End/PostAPI/DTO/Post.swift
  Plinic/Back-End/PostAPI/DTO/PostDetail.swift
  Plinic/Back-End/PostAPI/PostAPI.swift
  Plinic/Back-End/PostDetailData.swift
  Plinic/ContentView.swift
  Plinic/Navigation/PostView.swift
  Plinic/Navigation/Search.swift
  Plinic/Navigation/UserView.swift
  Plinic/Post/PostDetail.swift
  Plinic/Post/PostDetailView.swift
  Plinic/Post/PostViews/PostDetailInfoView.swift
  Plinic/Post/PostViews/PostHeader.swift
  Plinic/Post/PostViews/PostHeaderView.swift
  Plinic/Post/PostViews/PostView.swift
  Plinic/Post/postContentView.swift
  Plinic/User/UserViews/UserMyPostView.swift
Labels: 리팩토링, API, 개발

#68 :sparkles: :recycle: (feature/refactor), (feature/back-end/#53) API 모듈화 작업 & 리팩토링
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/Network/NetworkService.swift
  Plinic/Back-End/PostAPI/PostAPI.swift
  Plinic/Back-End/RandomAPI/DTO/BackgroundVideo.swift
  Plinic/Back-End/RandomAPI/RandomAPI.swift
  Plinic/Back-End/UserAPI/DTO/UserInfo.swift
  Plinic/Back-End/UserAPI/UserAPI.swift
  Plinic/Search/SearchViews/SearchDetail.swift
  Plinic/User/UserViews/UserInfoView.swift
  Plinic/User/UserViews/UserMyPostView.swift
  Plinic/User/userContentView.swift
  Plinic/VideoBackground/VideoBackgroundView.swift
Labels: 리팩토링, API

#72 (feature/back-end/#53) 가장 최근 생성된 공지사항 게시물 네비게이션 처리
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/CommonAPI/DTO/Genre.swift
  Plinic/Back-End/NoticeAPI/DTO/RecentNotice.swift
  Plinic/Post/PostDetailView.swift
  Plinic/Post/PostViews/PostHeaderView.swift
  Plinic/Search/searchContentView.swift
  Plinic/User/UserPlaylist.swift
  Plinic/WebViews/WebView.swift
Labels: 리팩토링, API, 개발

#75 :recycle: (jaewoo/feature/back-end/#74) 변수명,뷰 이름 수정
  Plinic.xcodeproj/project.pbxproj
  Plinic/Search/SearchViews/SearchResultView.swift
  Plinic/Search/SearchViews/searchBar.swift
Labels: 리팩토링, 개발

#76 (feature/login) 앱 실행 시 로그인 플로우 구성 #73 & 그 외 관련 파일 리팩토링 수행
  Plinic.xcodeproj/project.pbxproj
  Plinic/Application/ContentView.swift
  Plinic/Application/MainTabBarView.swift
  Plinic/Application/MyAppDelegate.swift
  Plinic/Application/MySceneDelegate.swift
  Plinic/Application/PlinicApp.swift
  Plinic/Info.plist
  Plinic/Login/KakaoAuthVM.swift
  Plinic/Login/LoginViews/LoginButton.swift
  Plinic/User/UserProfile.swift
Labels: 리팩토링, 개발

#77 (feature/back-end/#53) SearchContentView에서 장르를 탭하였을 때 뜨는 뷰
  Plinic.xcodeproj/project.pbxproj
  Plinic/Application/MainTabBarView.swift
  Plinic/Back-End/CommonAPI/DTO/Genre.swift
  Plinic/Back-End/CommonAPI/GenreAPI.swift
  Plinic/Search/SearchViews/GenreSearchView.swift
  Plinic/Search/searchContentView.swift
Labels: API, 개발

#78 (jaewon/feature/back-end/#53) 유저 정보 가져와서 뿌려주는 부분 일부 구현
  Plinic.xcodeproj/project.pbxproj
  Plinic/Application/MainTabBarView.swift
  Plinic/Back-End/Network/NetworkService.swift
  Plinic/Back-End/UserAPI/DTO/UserInfo.swift
  Plinic/Search/SearchViews/SearchDetail.swift
  Plinic/Search/SearchViews/SearchResultView.swift
  Plinic/Search/SearchViews/userTopResult.swift
  Plinic/Search/searchContentView.swift
  Plinic/User/UserProfileEditView.swift
  Plinic/User/UserViews/UserContents.swift
  Plinic/User/UserViews/UserInfoView.swift
  Plinic/User/userContentView.swift
Labels: API, 개발

#80 ⚡ (jaewon/feature/back-end/#53) 네트워크 통신 모듈 보완 & 자잘한 리팩토링 & 홈화면의 공개/비공개 플레이리스트 구현
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/Network/NetworkService.swift
  Plinic/Back-End/PlaylistAPI/PlaylistAPI.swift
  Plinic/Back-End/PostAPI/DTO/PlaylistDetial.swift
  Plinic/Back-End/PostAPI/DTO/PostDetail.swift
  Plinic/Back-End/UserAPI/DTO/UserInfo.swift
  Plinic/Post/postCreate.swift
  Plinic/Search/SearchViews/SearchResultView.swift
  Plinic/User/PlaylistCreateView.swift
  Plinic/User/UserPlaylist.swift
  Plinic/User/UserViews/PlaylistInfoView.swift
  Plinic/User/UserViews/ThumbnailView.swift
  Plinic/User/UserViews/UserMyPlaylistView.swift
  Plinic/User/UserViews/UserMyPostView.swift
  Plinic/User/userContentView.swift
Labels: 리팩토링, API, 개발

#84 (feature/back-end) PostCreateView에 공개된 플레이리스트 정보 통신
  Plinic.xcodeproj/project.pbxproj
  Plinic/Post/PostCreateView.swift
  Plinic/Post/PostViews/PostHeaderView.swift
  Plinic/Search/SearchViews/GenreSearchView.swift
  Plinic/User/UserViews/ThumbnailView.swift
Labels: API

#87 :recycle: (jaewon/feature/refactor) 검색 관련 뷰를 구현할 때 편하도록 리팩토링
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/PostAPI/DTO/Post.swift
  Plinic/Post/postContentView.swift
  Plinic/Search/SearchViews/GenreSearchView.swift
  Plinic/Search/SearchViews/MoreUserResultsView.swift
  Plinic/Search/SearchViews/SearchResultView.swift
Labels: 리팩토링

#89 아아아아 너무 힘들었따아아아아 좀만 쉬다 올게요오오오
  Plinic/Application/MainTabBarView.swift
  Plinic/Back-End/PostAPI/DTO/Post.swift
  Plinic/Back-End/PostAPI/DTO/PostDetail.swift
  Plinic/Back-End/UserAPI/DTO/UserInfo.swift
  Plinic/Post/PostDetailView.swift
  Plinic/Post/PostViews/PostView.swift
  Plinic/Post/postContentView.swift
  Plinic/Search/SearchViews/GenreSearchView.swift
  Plinic/Search/SearchViews/SearchResultView.swift
  Plinic/Search/SearchViews/searchBar.swift
  Plinic/User/UserViews/UserInfoView.swift
  Plinic/User/UserViews/UserMyPostView.swift
  Plinic/User/userContentView.swift
Labels: 리팩토링, 개발

#91 :art: :zap: (jaewoo/feature/refactor/#85/#86) PostCreateView 변경 사항
  Plinic/Post/PostCreateView.swift
  Plinic/Post/PostViews/PostDetailInfoView.swift
  Plinic/Search/SearchViews/GenreSearchView.swift
  Plinic/Search/SearchViews/GenreThumbnail.swift
  Plinic/Search/searchContentView.swift
  Plinic/User/UserViews/ThumbnailView.swift
  Plinic/User/UserViews/UserMyPostView.swift
Labels: 디자인, 리팩토링, 개발

#93 폴더 구조 변경 & View 가 보여주는 정보 Model 로 통합 & 작은 버그 수정
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/PostAPI/DTO/Post.swift
  Plinic/Back-End/PostAPI/DTO/PostDetail.swift
  Plinic/Views/Common/GenreTagView.swift
  Plinic/Views/Common/ThumbnailView.swift
  Plinic/Views/Common/VideoBackgroundView.swift
  Plinic/Views/Common/WebView.swift
  Plinic/Views/Login/Components/LoginButton.swift
  Plinic/Views/Login/ViewModel/KakaoAuthVM.swift
  Plinic/Views/Login/loginContentView.swift
  Plinic/Views/Post/PostViews/PostCreateView.swift
  Plinic/Views/Post/PostViews/PostDetailInfoView.swift
  Plinic/Views/Post/PostViews/PostDetailView.swift
  Plinic/Views/Post/PostViews/PostHeaderView.swift
  Plinic/Views/Post/PostViews/PostView.swift
  Plinic/Views/Post/postContentView.swift
  Plinic/Views/Search/SearchContentView.swift
  Plinic/Views/Search/SearchViews/GenreSearchView.swift
  Plinic/Views/Search/SearchViews/GenreThumbnail.swift
  Plinic/Views/Search/SearchViews/MoreUserResultsView.swift
  Plinic/Views/Search/SearchViews/SearchResultView.swift
  Plinic/Views/Search/SearchViews/UserResult.swift
  Plinic/Views/Search/SearchViews/searchBar.swift
  Plinic/Views/Search/SearchViews/userTopResult.swift
  Plinic/Views/User/PlaylistCreateView.swift
  Plinic/Views/User/UserPlaylist.swift
  Plinic/Views/User/UserProfileEditView.swift
  Plinic/Views/User/UserViews/PlaylistInfoView.swift
  Plinic/Views/User/UserViews/UserContents.swift
  Plinic/Views/User/UserViews/UserCountsView.swift
  Plinic/Views/User/UserViews/UserInfoView.swift
  Plinic/Views/User/UserViews/UserMyPlaylistView.swift
  Plinic/Views/User/UserViews/UserMyPostView.swift
  Plinic/Views/User/UserViews/chooseGenre.swift
  Plinic/Views/User/userContentView.swift
Labels: 리팩토링

#94 (/feature/back-end/#82) ImagePicker 추가
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/UserAPI/DTO/UserInfo.swift
  Plinic/Extensions/UIImage+.swift
  Plinic/Views/Common/ImagePicker.swift
  Plinic/Views/User/PlaylistCreateView.swift
  Plinic/Views/User/UserProfileEditView.swift
Labels: 리팩토링, 개발

#96 :sparkles: (jaewon/feature/back-end) 검색 API 구현 #74 & 검색 결과화면에서 데이터 뿌려주기
  Plinic.xcodeproj/project.pbxproj
  Plinic/Back-End/SearchAPI/DTO/SearchResult.swift
  Plinic/Back-End/SearchAPI/SearchAPI.swift
  Plinic/Views/Search/SearchViews/MoreUserResultsView.swift
  Plinic/Views/Search/SearchViews/SearchResultView.swift
  Plinic/Views/Search/SearchViews/searchBar.swift
Labels: API, 개발

#97 (feature/refactor/#82) 플레이리스트 생성 시에 썸네일 생성 랜덤으로 하는 기능(아직 POST 구현 X)
  Plinic/Back-End/RandomAPI/RandomAPI.swift
  Plinic/Views/Common/ThumbnailView.swift
  Plinic/Views/User/PlaylistCreateView.swift
Labels: 리팩토링, API, 개발

#100 서버쪽 데이터로 테스트 해보면서 발생한, 발생했던 문제 해결
  Plinic/Back-End/Network/NetworkService.swift
  Plinic/Back-End/NoticeAPI/NoticeAPI.swift
  Plinic/Back-End/PostAPI/DTO/PlaylistDetial.swift
  Plinic/Back-End/PostAPI/PostAPI.swift
  Plinic/Views/Login/Components/LoginButton.swift
  Plinic/Views/Post/PostViews/PostDetailInfoView.swift
  Plinic/Views/Post/PostViews/PostDetailView.swift
  Plinic/Views/Post/PostViews/PostView.swift
  Plinic/Views/User/UserViews/PlaylistInfoView.swift
Labels: API

#106 :art: (jaewoo/feature/refactor/#103) Image() 뷰를 모두 AsyncImage() 형태로 전환
  Plinic/Views/Post/PostViews/PostDetailInfoView.swift
  Plinic/Views/Post/PostViews/PostView.swift
  Plinic/Views/Search/SearchViews/GenreSearchView.swift
  Plinic/Views/Search/SearchViews/GenreThumbnail.swift
  Plinic/Views/Search/SearchViews/UserResult.swift
Labels: 리팩토링, 개발

#121 개발하는데 유용한 환경 세팅 & 이슈 #70 해결
  Plinic.xcodeproj/project.pbxproj
  Plinic.xcodeproj/xcshareddata/xcschemes/Plinic.debug.xcscheme
  Plinic.xcodeproj/xcshareddata/xcschemes/Plinic.release.xcscheme
  Plinic/Back-End/Common/DefaultJsonDecoder.swift
  Plinic/Back-End/CommonAPI/GenreAPI.swift
  Plinic/Extensions/Logger+.swift
  Plinic/Views/Common/ThumbnailView.swift
  Plinic/Views/Search/SearchContentView.swift
  Plinic/Views/User/PlaylistCreateView.swift
  Plinic/Views/User/UserProfileEditView.swift
  Plinic/Views/User/UserViews/UserPostView.swift
  Plinic/Views/User/userContentView.swift
Labels: 디자인, 리팩토링, API, 개발
